### ISSUE TITLE
Ligatures don't work on Terminal.app, Fira Code's do

### ISSUE THREAD

**Issue by AuroraWright** [kiliman/operator-mono-lig#40]
After patching the font using this program and selecting it in Terminal.app on macOS, ligatures don't show up, while they do with Fira Code.
Otherwise, they work fine using Sublime Text.

**Comment by kiliman** [comment]
Thanks for the report. Fira Code uses a different method for generating ligatures than I do. I'm not an expert in OpenType, so I wasn't aware there was a difference. 

I just ordered a book that goes into more detail. I hope to be able to replicate the way Fira Code works. Things like being able to move the carat (insertion point) inside the ligature (#35) as well as not converting long sequences into ligatures (e.g. ===== or +++++) (#37).

I'll keep you updated on the progress.

**Comment by kiliman** [comment]
This has been fixed in new branch features/contextsubst. It builds the fonts just like Fira Code.

NOTE: This only includes the Operator Mono ScreenSmart Book and Book Italic versions. This update was mainly for testing the new build process.

**Comment by haakonstorm** [comment]
Will Operator Mono give ligatures in Rstudio? (v1.1 or v1.2?)

**Comment by ProfKache** [comment]
Still doesn't work for me till now. Only Fira code works with ligatures.
